#!/bin/bash
#This is just going to pop open another window with a the gif in a loop. BTW, if you WM doesn't allow for swallowing its gonna look goofy deal with it. 
curl https://radar.weather.gov/ridge/standard/KTYX_loop.gif -o /tmp/sat && mpv /tmp/sat --vf=sub,lavfi="negate"  --loop=inf --no-border --osc=no
