#!/bin/bash
#This is just going to pop open another window with a the gif in a loop. BTW, if you WM doesn't allow for swallowing its gonna look goofy deal with it. 
mpv --loop-file=inf "https://radar.weather.gov/lite/N1P/TYX_loop.gif" 
